### ISSUE TITLE
policycoreutils

### ISSUE THREAD

**Issue by tburow** [ansible-lockdown/AMAZON2023-CIS#12]
**Question**
keep getting this error - seems to happen when things moved from 2.7 to 3.x but also a pretty common error across multiple OS's.

`amazon-ebs.instance: TASK [ansible-security/roles/AMAZON2-CIS : PRELIM | Section 1.6 | Ensure SELinux is installed] ***
    amazon-ebs.instance: fatal: [default]: FAILED! => {"changed": false, "failures": ["No package policycoreutils-python available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}`

**Environment (please complete the following information):**

` ansible --version
ansible [core 2.15.4]
  config file = None
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/workspace/AMI-Builder/ami-al2023-commercial/ansible-venv/lib/python3.9/site-packages/ansible
  ansible collection location = /home/ec2-user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ec2-user/workspace/AMI-Builder/ami-al2023-commercial/ansible-venv/bin/ansible
  python version = 3.9.16 (main, Sep 29 2023, 03:37:09) [GCC 10.5.0 20230707 (Red Hat 10.5.0-1)] (/home/ec2-user/workspace/AMI-Builder/ami-al2023-commercial/ansible-venv/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True`

Thoughts? Suggestions?

im running this via packer against an AL2023 AMI 

here is the ansible setup im using
`    stage('Setup Python venv') {
      steps {
        echo "Setup venv and install ansible"
        sh '''
          rm -rf /tmp/pip-install-*
          python3.9 -m venv ansible-venv
          source ansible-venv/bin/activate
          pip3.9 install ansible selinux
          ansible --version
        '''
      }`

here is the packer Resource

`  provisioner "ansible" {
    playbook_file = "./ami-al2023-play.yml"
    use_proxy     = false
    extra_arguments = [ "--extra-vars", "ansible_python_interpreter=/usr/bin/python3                            amzn2023cis_selinux_enforce=${var.amzn2023cis_selinux_enforce}" ]
  }`

**Comment by Ranjith219** [comment]
Hi @tburow - How did you resolve this issue? Could you please let me know? Thank you in advance.
