### ISSUE TITLE
Has anyone came across with syslog installation issue?

### ISSUE THREAD

**Issue by ashfaqsharif** [ansible-lockdown/AMAZON2023-CIS#16]
**Describe the Issue**
    amazon-ebs.al2023: TASK [harden-amazon-linux-2023 : 5.1.1.1 | PATCH | Ensure rsyslog installed] ***
    amazon-ebs.al2023: fatal: [default]: FAILED! => {"changed": false, "failures": ["No package rsyslog available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}

This is the control:

- name: "5.1.1.1 | PATCH | Ensure rsyslog installed"
  ansible.builtin.package:
      name: rsyslog
      state: present
  when:
      - "'rsyslog' not in ansible_facts.packages"
      - amzn2023cis_rule_5_1_1_1
  tags:
      - level1-server
      - patch
      - rsyslog
      - rule_5.1.1.1
      - nist_sp800-53r5_AU-3
      - nist_sp800-53r5_AU-12
      - nist_sp800-53r5_SI-5

I am able to install package using dnf directly:

[root@ip-10-10-10-67 bin]# dnf install rsyslog
Last metadata expiration check: 2:47:23 ago on Wed Oct 25 11:09:38 2023.
Dependencies resolved.
=============================================================================================================================================================================================================
 Package                                             Architecture                             Version                                                    Repository                                     Size
=============================================================================================================================================================================================================
Installing:
 rsyslog                                             x86_64                                   8.2204.0-3.amzn2023.0.4                                    amazonlinux                                   784 k
Installing dependencies:
 libestr                                             x86_64                                   0.1.11-1.amzn2023.0.2                                      amazonlinux                                    26 k
 libfastjson                                         x86_64                                   0.99.9-1.amzn2023.0.3                                      amazonlinux                                    39 k
Installing weak dependencies:
 rsyslog-logrotate                                   x86_64                                   8.2204.0-3.amzn2023.0.4                                    amazonlinux                                    10 k

Transaction Summary
=============================================================================================================================================================================================================
Install  4 Packages

Total download size: 859 k
Installed size: 2.8 M
Is this ok [y/N]: y
Downloading Packages:
(1/4): libestr-0.1.11-1.amzn2023.0.2.x86_64.rpm                                                                                                                              331 kB/s |  26 kB     00:00
(2/4): libfastjson-0.99.9-1.amzn2023.0.3.x86_64.rpm                                                                                                                          364 kB/s |  39 kB     00:00
(3/4): rsyslog-logrotate-8.2204.0-3.amzn2023.0.4.x86_64.rpm                                                                                                                  311 kB/s |  10 kB     00:00
(4/4): rsyslog-8.2204.0-3.amzn2023.0.4.x86_64.rpm                                                                                                                            5.6 MB/s | 784 kB     00:00
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                        4.1 MB/s | 859 kB     00:00
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                     1/1
  Installing       : libestr-0.1.11-1.amzn2023.0.2.x86_64                                                                                                                                                1/4
  Installing       : libfastjson-0.99.9-1.amzn2023.0.3.x86_64                                                                                                                                            2/4
  Installing       : rsyslog-logrotate-8.2204.0-3.amzn2023.0.4.x86_64                                                                                                                                    3/4
  Installing       : rsyslog-8.2204.0-3.amzn2023.0.4.x86_64                                                                                                                                              4/4
  Running scriptlet: rsyslog-8.2204.0-3.amzn2023.0.4.x86_64                                                                                                                                              4/4
Created symlink /etc/systemd/system/multi-user.target.wants/rsyslog.service → /usr/lib/systemd/system/rsyslog.service.

  Verifying        : rsyslog-8.2204.0-3.amzn2023.0.4.x86_64                                                                                                                                              1/4
  Verifying        : libfastjson-0.99.9-1.amzn2023.0.3.x86_64                                                                                                                                            2/4
  Verifying        : libestr-0.1.11-1.amzn2023.0.2.x86_64                                                                                                                                                3/4
  Verifying        : rsyslog-logrotate-8.2204.0-3.amzn2023.0.4.x86_64                                                                                                                                    4/4

Installed:
  libestr-0.1.11-1.amzn2023.0.2.x86_64          libfastjson-0.99.9-1.amzn2023.0.3.x86_64          rsyslog-8.2204.0-3.amzn2023.0.4.x86_64          rsyslog-logrotate-8.2204.0-3.amzn2023.0.4.x86_64

Complete!

**Comment by Ranjith219** [comment]
Hi @ashfaqsharif  - How did you resolve this issue? Could you please let me know? Thank you in advance.
