### ISSUE TITLE
Instance dont start after appling role due broken /etc/fstab

### ISSUE THREAD

**Issue by babinskiy** [ansible-lockdown/AMAZON2023-CIS#2]
**Describe the Issue**
After applying tasks for rule 1.4.1 to instance with secure boot (arm64) we have a broken `/etc/fstab`

**Expected Behavior**
Added permissions parameters to secureboot partition in `/etc/fstab`:

```diff
-  UUID=03D1-7AD6        /boot/efi       vfat    defaults,noatime,uid=0,gid=0,umask=0077,shortname=winnt,x-systemd.automount 0 2
+ UUID=03D1-7AD6        /boot/efi       vfat    defaults,umask=0027,fmask=0077,uid=0,gid=0 0 0
```

**Actual Behavior**
bad line for secure boot partition in `/etc/fstab`:

```diff
-  UUID=03D1-7AD6        /boot/efi       vfat    defaults,noatime,uid=0,gid=0,umask=0077,shortname=winnt,x-systemd.automount 0 2
+ <g>UUID=03D1-7AD6        /boot/efi       vfat    defaults,umask=0027,fmask=0077,uid=0,gid=0 0 0
```

**Control(s) Affected**
Instance switches to emergency boot mode after restart 

**Environment (please complete the following information):**
- branch being used: devel
- Ansible Version: 2.15
- Host Python Version: Python 3.9.16
- Additional Details: Instance Arch: Aarch64

**Comment by uk-bolly** [comment]
Hi @babinskiy 

Thank you for taking the time to raise this issue. I can see this is for arm64, CIS is written for x86_64. We can look at adding arm options but we will need feedback from the community on this.
We can make options with =arch possibly and this maybe a good way to approach this with this new benchmark.

We will discuss it internally and see if this is something we can add in.

many thanks

uk-bolly

**Comment by babinskiy** [comment]
Hi @uk-bolly 

Thanks for pointing out that this role is written for x86_64, but `<g>\1` is a wrong expression independently of architecture.

Im interested in using this role with `arm64` so I will continue testing and report any issues I find

Thanks for your work and generously sharing the outcomes of your efforts.

**Comment by uk-bolly** [comment]
hi @babinskiy 

Thank you for you very quick response and again for feeding back.
That is indeed a great catch for the bootloader. I am adding a new branch now with PR to fix this issue.

Thanks again 

uk-bolly

**Comment by uk-bolly** [comment]
hi @babinskiy 

Thank you fagian for raising this issue, i am hoping that this is now resolved in can be found in the devel and main branches.

many thanks

uk-bolly

**Comment by babinskiy** [comment]
Thanks @uk-bolly!
Yes this issue is resolved now!
