### ISSUE TITLE
consistent tag for ansible-galaxy

### ISSUE THREAD

**Issue by jouve** [ansible-lockdown/AMAZON2023-CIS#72]
**Describe the Issue**

The last tag created is named differently than the previous ones (no `v` prefix) :
* 1.1.0
* v1.0.0
* v0.9.0

when I try to install the role, it creates the following error:

```
% ansible-galaxy role install MindPointGroup.amazon2023_cis
Starting galaxy role install process
- downloading role 'amazon2023_cis', owned by MindPointGroup
[WARNING]: - MindPointGroup.amazon2023_cis was NOT installed successfully: Unable to compare role versions (v0.9.0, v1.0.0, 1.1.0) to determine the most recent version due to incompatible
version formats. Please contact the role author to resolve versioning conflicts, or specify an explicit role version to install.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**Expected Behavior**

consistent naming :)

**Actual Behavior**

naming differs

**Control(s) Affected**

What controls are being affected by the issue

**Environment (please complete the following information):**

- branch being used: galaxy
- Ansible Version: 2.16.5
- Host Python Version: 3.12
- Ansible Server Python Version: 3.12.3
- Additional Details:

**Additional Notes**

workaround is to specify the version : `ansible-galaxy role install MindPointGroup.amazon2023_cis,1.1.0`

**Possible Solution**

recreate the release on the same commit, but with v1.1.0 tag

**Comment by uk-bolly** [comment]
hi @jouve Jouve

Apologies, the decision was made to move all tags without the v prefix for all the managed repos last year. So this will be the standard going forward.Thank you for highlighting this, we will be adding this as a comment on the community as this could have be better communicated.

Many thanks

uk-bolly
