### ISSUE TITLE
1.2.4 incorrectly running for Server Level  1 profile

### ISSUE THREAD

**Issue by edjackson-wf** [ansible-lockdown/AMAZON2023-CIS#88]
**Describe the Issue**
1.2.4 is incorrectly included for `level1-server` profile. The CIS benchmark document specifies "Level 2 - Server" as the profile applicability for this rule.

**Expected Behavior**
When running with the `level1-server` tag, 1.2.4 should be skipped. Subsequent `dnf` tasks that interact with AL2023's default repositories should not fail due to missing GPG signatures (which are not provided by AWS).

**Actual Behavior**
1.2.4 is running with the `level1-server` tag. Without further workarounds, this causes subsequent `dnf` tasks to fail due to missing GPG signatures.

**Control(s) Affected**
1.2.4

**Environment (please complete the following information):**

- branch being used: devel
- Ansible Version: 2.17.3
- Host Python Version: Python 3.9.16
- Ansible Server Python Version: Python 3.12.1
- Additional Details: Using test environment — VirtualBox via Vagrant (box created from most recent AL2023 release)

**Additional Notes**
Workaround is to skip this rule explicitly.

**Possible Solution**
Change tag on the 1.2.4 block from `level1-server` to `level2-server`.

**Comment by uk-bolly** [comment]
hi @edjackson-wf 

Thank you for taking the time to raise this issue.
Great spot PR is being raised to merge to devel and fix this.

Many. thanks

uk-bolly

**Comment by uk-bolly** [comment]
Merged to main
Thank you

uk-bolly
